### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by JPerkster** [dvassallo/s3-benchmark#4]
Howdy,

Great tool, thanks so much. I'm also interested in how you built the Analysis XLS. Would you be able to share that?

**Comment by dvassallo** [comment]
It's not that complex actually. There are 3 Excel features being used: Pivot tables, PivotChart Analyze, and Slicers. The benchmarking tool already generates results in CSV, so the Raw Data sheet is just that. Then all the other sheets have a pivot table starting at column H based on the raw data. Pivot tables basically allow you to run something conceptually similar to an SQL query against the data. I used to to group the results by thread count, instance type, or object size (depending on the sheet). Then the main chart is done via a PivotChart. It's basically just a regular Excel chart but linked to the results of a pivot table instead of regular cells & columns. Finally, the selectors to the right of the chart are called Slicers. These are an extension of pivot tables, and allow you to have slightly fancier filters. When you use them, you're basically adjusting the pivot table query.

That's pretty much it. I hope that helps. Happy to answer more questions if there's any.
